version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my_teacher_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_CHARACTER_SET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - teacher_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_teacher_web
    restart: always
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      SECRET_KEY: ${SECRET_KEY}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - teacher_network
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: my_teacher_bot
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      WEBAPP_URL: ${WEBAPP_URL:-http://localhost:5000/schedule}
      LOG_GROUP_ID: ${LOG_GROUP_ID}
      TZ: Asia/Dubai
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - teacher_network

networks:
  teacher_network:
    driver: bridge

volumes:
  mysql_data: